### ISSUE TITLE
Disable user registration

### ISSUE THREAD

**Issue by mrandyyp** [MoonRivers21/taskAppFilament#1]
Hi Nick, I love this app. Can you help me, how to disable a new user registration?

**Comment by nick0221** [comment]
Hi thanks for your interest in my task app.

If you want to disable user registration in your task app by editing the `AdminPanelProviders.php` file. To do so, you can follow these steps:

1. Locate the `AdminPanelProviders.php` file in your app folder.
2. Look for the `registration()` method within the file.
3. Comment out or remove the code related to user registration within the `registration()` method.

If you encounter any issues or need further clarification, feel free to provide more details so that I can assist you accordingly.

Dont forget to hit the star button if you like the app.

**Comment by mrandyyp** [comment]
> Hi thanks for your interest in my task app.
> 
> If you want to disable user registration in your task app by editing the `AdminPanelProviders.php` file. To do so, you can follow these steps:
> 
> 1. Locate the `AdminPanelProviders.php` file in your app folder.
> 2. Look for the `registration()` method within the file.
> 3. Comment out or remove the code related to user registration within the `registration()` method.
> 
> If you encounter any issues or need further clarification, feel free to provide more details so that I can assist you accordingly.
> 
> Dont forget to hit the star button if you like the app.

Amazing, it works! Thank you. Please keep it updated and add any features related to productivity.
